# Generated by Django 5.1.1 on 2024-09-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0002_remove_comment_recipe_comment_content_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
