# Generated by Django 5.1.1 on 2024-09-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0003_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board_games/'),
        ),
    ]
